# Generated by Django 5.0.6 on 2024-05-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservationmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='time',
            field=models.TextField(),
        ),
    ]
